### ISSUE TITLE
Example needed

### ISSUE THREAD

**Issue by cassiopagnoncelli** [graphile/postgraphile-apollo-server#1]
I'm posting an

[x] example request
[ ] question
[ ] bug report
[ ] feature request.

I'm wondering how to use it. Is there a full example anywhere as for delegating Apollo Server request directly to Postgraphile?

**Comment by benjie** [comment]
Did you see the example linked in the README? https://github.com/graphile/postgraphile-example-apollo-server

If that’s not sufficient, could you expand on what you need?

**Comment by cassiopagnoncelli** [comment]
Read and tried, but not really what I was looking for.

I'd like to send Postgraphile query from an Apollo Server resolver, preferably using the lib (not HTTP). 

https://www.graphile.org/postgraphile/usage-schema/
Is this the answer? :)

**Comment by benjie** [comment]
Oh right; you don’t need this library for that. Indeed the link you have referenced is one way to achieve this 👍

**Comment by cassiopagnoncelli** [comment]
Brilliant! Based on your answer I'm convincing a friend to migrate, in this same fashion, from Prisma to Postgraphile.

> Indeed the link you have referenced is one way to achieve this 👍

Is there another documented way?

**Comment by benjie** [comment]
You could dispatch to a full postgraphile instance (rather than just the schema), or you could use something like https://github.com/artetecha/basic-binding

I think the schema-only route probably suits your needs given what you’ve said though 👍

Do join our chat: http://discord.gg/graphile

**Comment by cassiopagnoncelli** [comment]
Super, thanks! I'm in.
